services:
  app:
    image: notion-clone:latest
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/notion-clone-db

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: