name: CI/CD Pipeline # CI/CD 管道名稱

on: # 觸發條件
  push: # 當推送到以下分支時觸發
    branches:
      - main # 主分支
  pull_request: # 當拉取請求到以下分支時觸發
    branches:
      - main # 主分支

jobs: # 工作
  build: # 建構工作
    runs-on: ubuntu-latest # 在最新的 Ubuntu 上運行

    steps: # 步驟
      - name: Checkout code # 檢出代碼
        uses: actions/checkout@v4 # 使用 actions/checkout@v4

      - name: Set up SSH key # 設置 SSH 金鑰
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_notion_clone
          chmod 600 ~/.ssh/id_rsa_notion_clone

      # 測試階段：拉取最新代碼、停止已存在的容器、啟動容器、運行測試並清理
      - name: Run tests on EC2 instance
        run: |
          ssh -i ~/.ssh/id_rsa_notion_clone -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} "
            echo 'Entering project directory...'
            cd ~/notion-clone-project &&
            echo 'Stopping existing test containers...'
            sudo docker-compose -f docker-compose.test.yml down --remove-orphans &&
            echo 'Pulling latest code from GitHub...'
            git pull origin main &&
            echo 'Starting test containers...'
            sudo docker-compose -f docker-compose.test.yml up -d --remove-orphans &&
            echo 'Waiting for containers to start...'
            sleep 20 &&
            echo 'Running tests...'
            sudo docker exec notion-clone-project_app_1 npm test -- --watch=false
          "

      - name: Stop and remove test containers # 停止並移除測試容器
        run: |
          ssh -i ~/.ssh/id_rsa_notion_clone -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} "
            echo 'Navigating to project directory...'
            cd ~/notion-clone-project &&
            echo 'Stopping and removing test containers...'
            sudo docker-compose -f docker-compose.test.yml down --remove-orphans
          "

      - name: Deploy to server # 部署到伺服器
        run: |
          echo "Starting deployment..."
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_notion_clone
          chmod 600 ~/.ssh/id_rsa_notion_clone
          ssh -i ~/.ssh/id_rsa_notion_clone -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} "
            echo 'Navigating to project directory...'
            cd ~/notion-clone-project &&
            echo 'Stopping existing containers...'
            sudo docker-compose down --remove-orphans &&
            echo 'Building and starting Docker Compose...'
            sudo docker-compose up --build -d --remove-orphans &&
            echo 'Cleaning up unused Docker data...'
            sudo docker system prune -f
          "
          echo "Deployment finished."
        env: # 環境變量
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # SSH 私鑰