name: CI/CD Pipeline # CI/CD 管道名稱

on: # 觸發條件
  push: # 當推送到以下分支時觸發
    branches:
      - main # 主分支
      - ci-cd-add-unit-test # 設置 CI/CD 的分支
  pull_request: # 當拉取請求到以下分支時觸發
    branches:
      - main # 主分支

jobs: # 工作
  build: # 建構工作
    runs-on: ubuntu-latest # 在最新的 Ubuntu 上運行

    steps: # 步驟
      - name: Checkout code # 檢出代碼
        uses: actions/checkout@v4 # 使用 actions/checkout@v4

      - name: Set up SSH key # 設置 SSH 金鑰
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_notion_clone
          chmod 600 ~/.ssh/id_rsa_notion_clone

      - name: Test SSH connection # 測試 SSH 連接
        run: |
          ssh -i ~/.ssh/id_rsa_notion_clone -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} "echo 'SSH connection successful'"
          echo "SSH connection test finished."

      - name: Run unit tests in Docker Compose # 在 Docker Compose 中運行單元測試
        run: |
          echo "Starting unit tests..."
          echo "Connecting to EC2 instance..."
          ssh -i ~/.ssh/id_rsa_notion_clone -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} "
            echo 'Changing directory to notion-clone-project...'
            cd ~/notion-clone-project &&
            echo 'Running Docker Compose for tests...'
            sudo docker-compose -f docker-compose.test.yml up --abort-on-container-exit || exit 1 &&
            echo 'Waiting for containers to start...'
            sleep 15 &&
            echo 'Stopping and removing test containers...'
            sudo docker-compose -f docker-compose.test.yml down
          "
        env: # 環境變量
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # SSH 私鑰

      - name: Deploy to server # 部署到伺服器
        run: |
          echo "Starting deployment..."
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_notion_clone
          chmod 600 ~/.ssh/id_rsa_notion_clone
          ssh -i ~/.ssh/id_rsa_notion_clone -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} "
            echo 'Navigating to project directory...'
            cd ~/notion-clone-project &&
            echo 'Pulling latest code from GitHub...'
            git pull origin main &&
            echo 'Stopping existing containers...'
            sudo docker-compose down &&
            echo 'Building and starting Docker Compose...'
            sudo docker-compose up --build -d &&
            echo 'Cleaning up unused Docker data...'
            sudo docker system prune -f
          "
          echo "Deployment finished."
        env: # 環境變量
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # SSH 私鑰